#!/bin/sh

usage(){
	echo "\nUsage: ovfindex-gen <repo URL> <repo name>\n"
}

if [ -z "$1" ]; then
	usage
fi

if [ -z "$2" ]; then
	usage
fi

java -jar /opt/abiquo/tools/ovfindex-gen/lib/indexgenerator-0.1.jar /var/www/html/ "$1" "$2" /var/www/html/ovfindex.xml

